### ISSUE TITLE
Development Questions

### ISSUE THREAD

**Issue by KillerInk** [obs1dium/BetterManual#8]
Hi what I still miss is bulb shooting to start with the EnterKey.
Play with it now for two days but it does not get to run.
With the touchlessRemote it seem to trigger the s2Key

```
public int pushedS2Key()
  {
    ExecutorCreator.getInstance().getSequence().inquireKey(518);
    return 1;
  }
```
BaseShootingExecutor
`public abstract void inquireKey(int paramInt);`

but that inquireKey() is not implemented and just an abstract stub.
So i tryed to inject keys with Instrumentation() and Activity.dispatchKeyEvent() but non works.
The injected event gets called inside the activity, but does not lock the s2 key down.

Maybe you have an idea.
greets

**Comment by KillerInk** [comment]
I finaly understood. with bulb active, the onShutter callback is repeating called . i had there a cancelTakePicture() inside wich stopped it.

**Comment by obs1dium** [comment]
Sorry, hadn't tried bulb shooting yet. I think you must call cancelTakePicture for "normal" shutter speeds, though.

**Comment by KillerInk** [comment]
Yes cancelTakePicture must be called after each capture. And for Bulb only when it should finish.
Thx for your work sofar.

**Comment by obs1dium** [comment]
I see you're working on some much-needed refactoring and code cleanup :)

**Comment by KillerInk** [comment]
Yes the code has it urgently necessary 👍 
But with adb the development flow has total changed. @ma1co is a hero

I'm just hanging out at the ImagePreview. Direct loading of bitmaps is slow.
Sony uses the OptimizedImageView and OptimizedImageFactory to load it.
The _data collumn from ContentProvider seems to be the wrong one. Its return an empty OptimizedImage. But works with the BitmapFactory....
The AvIndexStore contains a Folder Object, maybe that returns the direct path.
No idea why they have made this so complicated.

path from _data:
`avindex://1000/00000001-default/00000001-00000925`

end in:
```
I/StillPlayHAL: decodeImage() target:0x0036bcf0 imageType:2 uri:1000/00000001-default/00000001-00000925 colorType:1
I/StillPlayHAL: decodeImage() ticket:0xf0000000 errCd:0x00001004
```


thats from base app, i miss something
```
D/FACTORY_CLASS: Start: decodeImage(String uri, Options options)
D/FACTORY_CLASS: JNI call
I/StillPlayHAL: decodeImage() target:0x000bd480 imageType:2 uri:1000/00000001-default/00000019-000009E0 colorType:1
I/StillPlayHAL: decodeImage() ticket:0x10000801 errCd:0x00000000
I/SDCom: [A:1773] SDCom: 05:01:37 May 26 2016
I/SDCom: [A:1773] msgqId(RX): 0x1586100
I/MetaUtil: CreatePlayContentInfo() CopyBuffer [912]
D/FACTORY_CLASS: JNI called
D/FACTORY_CLASS: 1000/00000001-default/00000019-000009E0
AVIndexProvider: decode time : 111
```

**Comment by KillerInk** [comment]
have it working. the camera need to get closed...^^

**Comment by KillerInk** [comment]
Stupid question, but where did you find that TextView Image Strings?

> ("**\uE4CD** to set timelapse interval, **\uE04C** to confirm");

**Comment by KillerInk** [comment]
Found them inside framework-res.

**Comment by obs1dium** [comment]
The default font is Sony_DI_Icons.ttf, I used a font viewer to look for useful characters.

Didn't realize adb was working now, I'll have to take a look at that once I have some time to spare.

**Comment by KillerInk** [comment]
With opening the Camera in Background a new problem happened.
All Callbacks from Camera run now in that Thread. 
Due that, after a Capture the AvIndexUpdate seems to stuck somehow, and the red light turn only off with closing the app. 
Then you see in Log that it get updated..... 
```
01-01 00:22:59.746 497-848/? I/_AvindexOsalReceiver_: onReceiveOsal# start
01-01 00:22:59.746 497-848/? I/_AvindexOsalReceiver_: RecvObjMsg messageId = 0x20003
01-01 00:22:59.746 497-848/? I/_AvindexOsalReceiver_:   send cond_signal.
01-01 00:22:59.746 497-848/? I/_AvindexOsalReceiver_: onReceiveOsal# end
01-01 00:22:59.746 497-847/? I/_AvindexOsalReceiver_:   waitEventAndCallJavaMethod() received cond signal.
01-01 00:22:59.746 497-847/? I/_AvindexOsalReceiver_:   Call InfraScalarMprEventReceiver.onEvent().
01-01 00:22:59.748 497-847/? I/_AvindexOsalReceiver_:   waitEventAndCallJavaMethod() start waiting...
01-01 00:22:59.767 497-848/? I/_AvindexOsalReceiver_: onReceiveOsal# start
01-01 00:22:59.768 497-848/? I/_AvindexOsalReceiver_: RecvObjMsg messageId = 0x20001
01-01 00:22:59.768 497-848/? I/_AvindexOsalReceiver_:   send cond_signal.
01-01 00:22:59.768 497-848/? I/_AvindexOsalReceiver_: onReceiveOsal# end
01-01 00:22:59.768 497-848/? I/_AvindexOsalReceiver_: onReceiveOsal# start
01-01 00:22:59.768 497-848/? I/_AvindexOsalReceiver_: RecvObjMsg messageId = 0x20003
01-01 00:22:59.768 497-848/? I/_AvindexOsalReceiver_:   send cond_signal.
01-01 00:22:59.768 497-848/? I/_AvindexOsalReceiver_: onReceiveOsal# end
01-01 00:22:59.768 497-847/? I/_AvindexOsalReceiver_:   waitEventAndCallJavaMethod() received cond signal.
01-01 00:22:59.768 497-847/? I/_AvindexOsalReceiver_:   Call InfraScalarMprEventReceiver.onEvent().
01-01 00:22:59.773 497-497/? D/AvindexProvider: onReceive()# action = com.sony.scalar.database.avindex.action.AVINDEX_DATABASE_UPDATED
01-01 00:22:59.830 497-847/? I/_AvindexOsalReceiver_:   Call InfraScalarMprEventReceiver.onEvent().
01-01 00:22:59.832 497-847/? I/_AvindexOsalReceiver_:   waitEventAndCallJavaMethod() start waiting...
```

That dont happen with camera opening in MainLooper. In log you see that it gets updated direct after a capture. And red light turn off.
Funny is that you can capture one by one without problems. But it freez the app when you open the imageviewer.
But the viewer opens fine aslong you dont capture and the red light is on.
Its crazy 🐰

**Comment by obs1dium** [comment]
I wouldn't be surprised if some things can only be done on the main thread. 

You're looking at the Sony apps as well, right? If I'm reading the code correctly, they're always opening the camera on the main thread (ExecutorCreator).

**Comment by KillerInk** [comment]
hm you're right, thx.
yes i look into sony apps too. well then i have to rework some stuff.

**Comment by KillerInk** [comment]
I created now a small app wich just opens the camera and handel the onShutter callback,
Code runs on MainThread and have same behavior as running in Background. So threading seems not to be a problem. Im out of ideas, that's not the behavior i expected.

https://github.com/KillerInk/OpenMemoriesCam/blob/master/app/src/main/java/openmemories/com/opencamera/MainActivity.java

**Comment by obs1dium** [comment]
The test app seems to work fine, can you add code to reproduce the bad behavior there?

**Comment by KillerInk** [comment]
Thats the code that cause it. maybe its a problem with the a6000. 
When i commit out all stuff from a BetterManual, that only the camera get open and the onShutter gets set, it works. Using the sample app, red light keep on till i close the app. It makes no sense.
I also tryed to update the avindex manual without success. database gets updated but red light keep on.
I thought that the support lib is causing it. but after removing it, its the same behavior.

**Comment by obs1dium** [comment]
I recently upgraded to an A6000 myself and used it to run the test app, the red light turned off shortly after taking a picture. Maybe the problem is caused by a particular camera setting?

**Comment by KillerInk** [comment]
I have no idea what it cause. Looks like mine is special. But good to know that it works for you. It stopped working for me after i added the fragment stuff. When i switch to your last commit its working. Its total crazy.

**Comment by obs1dium** [comment]
Looks like the problem occurs when image quality is set to RAW & JPEG. I usually shoot RAW only, so it didn't happen before.

**Comment by KillerInk** [comment]
I'm not at home and don't remember what picture format is set. Check it tomorrow.

**Comment by KillerInk** [comment]
With raw only it works. But with jpeg or raw/jpeg not. Big thx. Now i have something i can work with.

**Comment by Nebuleusesetcacao** [comment]
Hi, thank you a lot for this app. I use it on a A7sii, and it works great ! 
My question is concerning the BulbMode. How can we use it ? When i want to take a picture with it, i don"t know how i can select a time for the picture... Do you have an issue ?
I'm just looking for an app who can used the Bulb mode without the Noise Reduction, do you know an equivalent ? Thank you so much !

**Comment by obs1dium** [comment]
Exposure time in bulb mode simply depends on how long you press the shutter button. I don't know if long exposure noise reduction is disabled on the A7sii.

**Comment by Nebuleusesetcacao** [comment]
Yes, but the bulb mode is available in your App, is it a way to do a timelapse in bulb mode ?

**Comment by Nebuleusesetcacao** [comment]
I see that KillerInk make a update of Better Manual here : https://github.com/KillerInk/BetterManual
But, and i'm sorry about that, i'm not a coder... I used the pmcgui to install your App, and i don't know how i can install the KillerInk version...

**Comment by KillerInk** [comment]
Its only the source. I have not uploaded a release to my github. But its sofar stable and i use it to capture stars.
its not much left from the orginal code but @obs1dium is the owner of the repo. And what i read this repo is linked to the openmemories store.
so its the best place for releases. When he want i can open a pull request.

**Comment by obs1dium** [comment]
I wouldn't mind your app replacing this in OpenMemories or merging your code. However, I'd like to be sure that it still works properly with the a5100, which it was originally meant to be used with. I upgraded to an a6000 a while back and can't test it myself.

**Comment by lh8511** [comment]
I tried the code from @KillerInk  on Android studio and after installing I had big issues on a6300... The app keeps crashing! Maybe I was doing something wrong at some point.
BTW, the repo from @obs1dium was working (stable) on nex6 and a6300, but I did not test all features.

@obs1dium: I am developing a new app which your bettermanual code is the MOST of it... 
It takes your app main struture as interface but for another purpose. 
Can I publish as new repo and refering your work?

Thanks

**Comment by obs1dium** [comment]
Sure, go ahead, the code's under MIT license after all. If you think the app's useful to other people, open a pull request at [OpenMemories-AppList](https://github.com/ma1co/OpenMemories-AppList).

**Comment by lh8511** [comment]
@obs1dium 
Thank you Martin.
After run some more tests, I will publish the repository. Will also wait to get some feedback from people with other camera models (I can only test the app at nex6 and a6300), so then pull request at OpenMemories-Applist.

**Comment by KillerInk** [comment]
@lh8511 the only things that could cause a crash is that imageview stuff. 
There seems to be two ways. one use OptimizedImageFactory(gingerbread?) and other decode it to a bitmap(froyo?).
Or liveSlowShutter or longexposure noise reduction. i dont think its a big problem to get it working.
Need only the crash log.

One thing i missed, was to change easy the layout without opening a new activity.
With using different activitys the camera must get closed and reopen on the new activity if used.
also i wanted a preview for the taken images.

when you have questions or need help just ask. i will try my best

**Comment by lh8511** [comment]
@KillerInk,

You are probably correct about what is causing the crashs using your code, because they realy are two diferent android versions... I will check during the weekend! 
Also, need  check my android studio, because signed apks was causing troubles: I kept using _debug versions_ when compiling the code into apk!!! (Sorry, I am just learning java/android).

Regarding preview of taken image - are ou refering the review of n seconds  just after shoot or a new activity to display the "Media gallery"?

**Comment by KillerInk** [comment]
> You are probably correct about what is causing the crashs using your code, because they realy are two diferent android versions... I will check during the weekend!

It could be also the AvIndexManager, maico has there a class wich sort it out. But it was not able to get a optimized image with it.

> Also, need check my android studio, because signed apks was causing troubles: I kept using debug versions when compiling the code into apk!!! (Sorry, I am just learning java/android).

Aslong you are on the same pc the debug signed apk works. But a other pc creates a different debug key.
In that case you have to uninstall the app from the camera to install a different signed apk. I have more places to code, thats why i add by default a signed key.

> Regarding preview of taken image - are ou refering the review of n seconds just after shoot or a new activity to display the "Media gallery"?

I mean a "Media Gallery" where you can look through the last shoots.

**Comment by lh8511** [comment]
> I mean a "Media Gallery" where you can look through the last shoots.

Maybe you can use the one from [PMCADemo](github.com/ma1co/PMCADemo/blob/master/app/src/main/java/com/github/ma1co/pmcademo/app/PlaybackActivity.java)

**Comment by KillerInk** [comment]
Not on a6000. There the info.getPreviewImage returns null from pmca code. It was my first try, after that it looked how sony does it. Also im not sure if that works with raw images.

**Comment by KillerInk** [comment]
@lh8511 i changed the code, that it now checks with reflection if ithe AvIndexStore is supported.
if not it disable the Gallery. Hope that fix the crash

**Comment by lh8511** [comment]
Thanks @KillerInk.

**Comment by sapindac** [comment]
Have small questions about the application. How app turns red AF illumination, I didn't find anything in the code. Why this feature is used, and do you know how to avoid it?

**Comment by obs1dium** [comment]
That's a camera setting, you can turn it off in the menu (Camera Settings / AF Illuminator)

**Comment by sapindac** [comment]
I thought about this, but it's turned off on my camera all the time. Double checked - it turned off in the menu. Happens only in timelapse and bracketing mode. Something different here. Using on A7M2.

Thinking now its a self-timer indicator, but didn't see a way why it's fired on.

**Comment by m-kostrzewa** [comment]
> Looks like the problem occurs when image quality is set to RAW & JPEG. I usually shoot RAW only, so it didn't happen before.

> With raw only it works. But with jpeg or raw/jpeg not. Big thx. Now i have something i can work with.

Hi, I've been debugging an issue with `cameraEx.cancelTakePicture();` on a5000 and I found your comments helpful... however, it's the other way around for me. It works only with JPG and RAW+JPG. Just RAW crashes the app I've been debugging. App uses takePicture and cancelTakePicture to capture long exposures (bulb). Just FYI.

**Comment by KillerInk** [comment]
> Hi, I've been debugging an issue with `cameraEx.cancelTakePicture();` on a5000 and I found your comments helpful... however, it's the other way around for me. It works only with JPG and RAW+JPG. Just RAW crashes the app I've been debugging. App uses takePicture and cancelTakePicture to capture long exposures (bulb). Just FYI.

that problem went away on a6000 with updating the fw to 3.21

**Comment by m-kostrzewa** [comment]
My a5000 fw is 1.10 (I think it's the newest). I also have a7ii and no issue there. 

It is mentioned in this thread that it worked for a5100 in the past. That's how I made the logical jump that it should probably work similarly for my a5000. Not sure if it still works for a5100 or not.

In any case, should I just assume that "only RAW" not working is a firmware issue?

**Comment by KillerInk** [comment]
> 
> 
> My a5000 fw is 1.10 (I think it's the newest). I also have a7ii and no issue there.
> 
> It is mentioned in this thread that it worked for a5100 in the past. That's how I made the logical jump that it should probably work similarly for my a5000. Not sure if it still works for a5100 or not.
> 
> In any case, should I just assume that "only RAW" not working is a firmware issue?

you should not assume that. 
on orginal code it worked, with my changes not. i was not able to figure out whats causing it.
still think its somekind of settings combination wich breaks it.

**Comment by m-kostrzewa** [comment]
> on orginal code it worked, with my changes not.(..) still think its somekind of settings combination wich breaks it.

I assume you mean settings set by your code then? I set RAW+JPG outside of the app I'm testing (so, manually). Note, I'm not a user of BetterManual, so I'm not familiar with how it works.

Because JPG and RAW+JPG work, I have a suspicion it has something to do with previews.. Maybe a5000 does something weird when trying to prepare/show preview when ony RAW is available, but prefers JPG or something.

In the app I'm debugging there is the following snippet:
```
            cameraEx.cancelTakePicture();
            cameraEx.getNormalCamera().stopPreview();
```

but commenting out stopPreview() doesn't affect the application (i.e. it still crashes in the same way), so it's not the fault of showing the preview.

I think the app crashes inside cameraEx.cancelTakePicture(). Shutter close sound is heard, but then it crashes. I'm not familiar with internals of cancelTakePicture though but I suspect there is some special handling of only RAW (or rather, lack of JPG).

**Comment by KillerInk** [comment]
stopping preview is not needed. at least on a6000
something locked up the avosal. but i dont know what it caused. 
https://github.com/obs1dium/BetterManual/issues/8#issuecomment-331713511

**Comment by m-kostrzewa** [comment]
> I wouldn't be surprised if some things can only be done on the main thread.

Maybe this is the culprit. TakePicture and CancelTakePicture are both called in different Runnables, outside of main thread.

**Comment by m-kostrzewa** [comment]
It was fixed by calling TakePicture and CancelTakePicture in the same Runnable (not even in any of the activity handlers). 

Why does it work? No idea. I didn't see any race conditions in previous code. Anyways, thanks for help.

**Comment by KillerInk** [comment]
great you found it^^
think the race condition happen on native side and the native camera is threaded.

**Comment by thenickdude** [comment]
I get the hang with JPEG+RAW even if I put takePicture and cancelTakePicture in the same Runnable, works fine with just RAW though... Same thing if I use @KillerInk's fork. (A7R)

I really wish I could figure this out

**Comment by thenickdude** [comment]
Ahh it was hanging because I was setting the aspect ratio to 1:1, works fine with 3:2!

Edit: And in KillerInk's branch I had to remove this setColorDepth method in BaseActivity, or otherwise switching to RAW+JPEG made it hang forever after taking a pic:

```java
  protected void setColorDepth(boolean highQuality) {
      Gpelibrary.GS_FRAMEBUFFER_TYPE type = highQuality ? Gpelibrary.GS_FRAMEBUFFER_TYPE.ABGR8888 : Gpelibrary.GS_FRAMEBUFFER_TYPE.RGBA4444;
      Gpelibrary.changeFrameBufferPixel(type);
  }
```

**Comment by thenickdude** [comment]
Did anybody figure out how to import custom images into the AvIndexManager? I'd like to add JPEGs I've custom-generated myself to the playback library.

For me calling contentResolver.insert() triggers this exception:

```E/DatabaseUtils(  502): Writing exception to parcel
E/DatabaseUtils(  502): java.lang.UnsupportedOperationException
E/DatabaseUtils(  502): 	at com.sony.scalar.providers.avindex.AvindexProvider.insert(AvindexProvider.java:207)
E/DatabaseUtils(  502): 	at android.content.ContentProvider$Transport.insert(ContentProvider.java:198)
E/DatabaseUtils(  502): 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:146)
E/DatabaseUtils(  502): 	at android.os.Binder.execTransact(Binder.java:320)
E/DatabaseUtils(  502): 	at dalvik.system.NativeStart.run(Native Method)
W/dalvikvm( 1372): threadid=1: thread exiting with uncaught exception (group=0x4363560)
```

And indeed I checked out the code for AvindexProvider.insert() (thanks [to this hint](https://github.com/ma1co/OpenMemories-Tweak/issues/58)) and it just unconditionally throws UnsupportedOperationException, it looks like a dead end

**Comment by thenickdude** [comment]
Well, I got it to successfully import it into what must be the Android camera directory at `/mnt/sdcard/DCIM/Camera` by adapting the code of Android's `MediaStore.Images.Media::insertImage()` function to avoid loading the picture into memory (otherwise it killed the process due to being out of RAM):

```java
private static void copyStream(InputStream source, OutputStream target) throws IOException {
    byte[] buf = new byte[8192];
    int length;

    while ((length = source.read(buf)) > 0) {
        target.write(buf, 0, length);
    }
}

public static String importImage(ContentResolver contentResolver, File filename) {
    ContentValues values = new ContentValues();
    values.put(MediaStore.Images.Media.TITLE, "");
    values.put(MediaStore.Images.Media.DESCRIPTION, "");
    values.put(MediaStore.Images.Media.MIME_TYPE, "image/jpeg");

    Uri url = null;
    String stringUrl = null;

    try {
        url = contentResolver.insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI, values);

        OutputStream imageOut = contentResolver.openOutputStream(url);

        try {
            copyStream(new FileInputStream(filename), imageOut);
        } finally {
            imageOut.close();
        }

        long id = ContentUris.parseId(url);
        // Wait until MINI_KIND thumbnail is generated.
        Bitmap miniThumb = MediaStore.Images.Thumbnails.getThumbnail(contentResolver, id,
                MediaStore.Images.Thumbnails.MINI_KIND, null);
    } catch (Exception e) {
        Log.e(TAG, "Failed to insert image", e);
        if (url != null) {
            contentResolver.delete(url, null, null);
            url = null;
        }
    }

    if (url != null) {
        stringUrl = url.toString();
    }

    return stringUrl;
}
```

But it's not visible in the camera playback, and if I change the external content URI to what should be the correct one for Sony camera images `AvindexStore.Images.Media.EXTERNAL_CONTENT_URI`, I hit the same old UnsupportedOperationException again:

```
E/DatabaseUtils(  502): java.lang.UnsupportedOperationException
E/DatabaseUtils(  502): 	at com.sony.scalar.providers.avindex.AvindexProvider.insert(AvindexProvider.java:207)
E/DatabaseUtils(  502): 	at android.content.ContentProvider$Transport.insert(ContentProvider.java:198)
E/DatabaseUtils(  502): 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:146)
E/DatabaseUtils(  502): 	at android.os.Binder.execTransact(Binder.java:320)
E/DatabaseUtils(  502): 	at dalvik.system.NativeStart.run(Native Method)
```

**Comment by KillerInk** [comment]
hm when i remember correct not all devices can use **MediaStore.Images.Thumbnails.getThumbnail.**
on A6000 that method returns NULL.
had to use the **OptimizedImageFactory**


also i dont see that you set the DATA flag
`values.put(MediaStore.Images.Media.DATA, file.getAbsolutePath());`

also that should the applied
```
values.put(MediaStore.Images.Media.DATE_ADDED, (System.currentTimeMillis()/1000));
values.put(MediaStore.Images.Media.DATE_TAKEN, (System.currentTimeMillis()/1000));
values.put(MediaStore.Images.Media.DATE_MODIFIED, (System.currentTimeMillis()/1000));
```
else the image get dated to 1970 bla and appears as last

**Comment by thenickdude** [comment]
It seems to fail to write the thumbnails to disk at all, it first complains about being unable to create the /mnt/sdcard/DCIM/.thumbnails directory, but even if I create it for it it still fails to write any thumbnails to that directory:

```
E/DatabaseUtils( 2428): java.lang.IllegalStateException: Unable to create new file: /mnt/sdcard/DCIM/.thumbnails/2718288.jpg
E/DatabaseUtils( 2428): 	at com.android.providers.media.MediaProvider.ensureFile(MediaProvider.java:1718)
E/DatabaseUtils( 2428): 	at com.android.providers.media.MediaProvider.insertInternal(MediaProvider.java:1849)
E/DatabaseUtils( 2428): 	at com.android.providers.media.MediaProvider.insert(MediaProvider.java:1759)
E/DatabaseUtils( 2428): 	at android.content.ContentProvider$Transport.insert(ContentProvider.java:198)
E/DatabaseUtils( 2428): 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:146)
E/DatabaseUtils( 2428): 	at android.os.Binder.execTransact(Binder.java:320)
E/DatabaseUtils( 2428): 	at dalvik.system.NativeStart.run(Native Method)
```

This seems like it must be an Android permissions problem.

I can't set DATA as my image doesn't exist on disk at this point and so doesn't have a filename yet. I'm assuming it gets set for me internally, since a numbered filename gets allocated for me automatically.

Good tip on those dates!

**Comment by thenickdude** [comment]
Apparently the issue is that the filesystem implementation only supports 8 character long names, so Android fails to create a ".thumbnails" directory. Even if you create one using a PC, Android still can't use it, any attempt to cd into it, remove it, or create files below it fails:

<img width="244" alt="Screen Shot 2022-07-10 at 12 19 28 PM" src="https://user-images.githubusercontent.com/1921411/178126676-20ad7b64-b0a2-4550-a8de-1536eadeba34.png">

I guess this limitation comes from the fuse driver that mounts the SDCard:

    FuFsys /mnt/sdcard fuse.FuFsys rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0

This is unfortunate since the Android thumbnail store hardcodes the `/DCIM/.thumbnails` directory name.

EDIT: Oh, it also requires filenames to be ALL UPPERCASE, lol. I had to transform the "data" addresses for the images like this to be able to open them:

```java
String filename = getData();
String storagePrefix = Environment.getExternalStorageDirectory().toString();

// Inside the SD card mount we're only allowed to access DOS-style 8.3 paths where all letters are capital!
filename = storagePrefix + filename.replace(storagePrefix, "").toUpperCase();
```

This is my completed project if anyone else wants to be able to do this:

https://github.com/Sherlock-Photography/QuantumMirror
